trigger:
- main

pool:
  name: Default
  demands: agent.name -equals agent01
stages:
  - stage: Build
    jobs:
      - job: Firstjob
        steps:
          - bash: echo Build first 
          - bash: echo $(pipelevelvarible)
          - bash: echo $(Build.BuildNumber)
          - bash: echo $(Build.BuildId)
          - bash: echo $(Build.SourceBranchName)
          - bash: echo $(Build.SourcesDirectory)
          - bash: echo ls -R $(System.DefaultWorkingDirectory)
          - bash: echo $(Build.ArtifactStagingDirectory)
      # - job: Secondjob
      #   steps:
      #     - bash: echo Build second job
  # - stage: DevDeploy
  #   variables:
  #     environment: Devdeploy
  #   dependsOn: Build
  #   jobs:
  #     - job: FirstJob
  #       steps:
  #         - bash: echo $(environment)
  # - stage: QADeploy
  #   variables:
  #     environment: QADeploy
  #   dependsOn: DevDeploy
  #   jobs:
  #     - job: FirstJob
  #       steps:
  #         - bash: echo $(environment)
  # - stage: ProductionDeploy
  #   variables:
  #    environment: ProductionDeploy
  #   dependsOn: QAdeploy
  #   jobs:
  #     - job: Firstjob
  #       steps:
  #         - bash: echo $(environment) 
